terry_api:
    event_listener: 
        array_response_listener:
            enable: true
        http_error_listener: 
            enable: true
        object_response_listener: 
            enable: true
    argument_value_resolver:
        abstract_http_client_resolver:
            enable: true
        single_object_resolver:
            enable: true
        objects_array_resolver:
            enable: true
    http_server:
        formats:
            json:
                - 'application/json'
            xml:
                - 'application/xml'
                - 'text/html'
        format_default: 'application/json'