version: "3.1"
services:
    webserver:
      image: nginx:alpine
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8040:80"
    php-fpm:
      build: docker/php-fpm
      working_dir: /app
      env_file:
        - ./docker/php-fpm/.env
      volumes:
        - ./vendor:/app/vendor:cached
        - .:/app
    db:
      image: postgres:11
      volumes:
        - ./docker/db/pg-init-scripts:/docker-entrypoint-initdb.d
      restart: always
      ports:
        - "8042:5432"
      environment:
        POSTGRES_MULTIPLE_DATABASES: app,app_test
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass