frontend:
    resource: ../../src/Infrastructure/Controller/FrontendController.php
    type: annotation
    prefix:
        de: 'de'
        en: 'en'

app:
    resource: ../../src/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
